# Generated by Django 3.1.7 on 2021-05-31 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210531_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='auction_listing',
            new_name='listing',
        ),
    ]
