# Generated by Django 3.1.7 on 2021-06-04 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210603_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='num_bids',
        ),
    ]
