# Generated by Django 3.1.7 on 2021-06-13 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210612_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='watched',
        ),
        migrations.AddField(
            model_name='listing',
            name='interested_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
